const items = [
    {
        date: "NOV 25-26",
        title: "Lakeside Camping at Pawna",
        type: "Adventure Geek - Explore the Unexplored, Mumbai",
        time: "8:30 AM - 7:30 PM",
        code: "INR 1,400",
        interested: "14 interested",
        image: "/public/images/Image1.png",
        starImage:"/public/images/Star 1.png",
    },
    {
        date: "NOV 02",
        title: "Sound Of Christmas  2023",
        type: "Sound Of Christmas  2023",
        time: "",
        code: "",
        interested: "16 interested",
        image: "/public/images/Image2.png",
        starImage:"/public/images/Star 1.png",
      },
      {
        date: "DEC 02",
        title: "Meet the Royal College of Art in Mumbai 2023",
        type: "Sofitel Mumbai BKC, Mumbai",
        time: "10 AM - 5 PM",
        code: "FREE .",
        image: "/public/images/Image3.png",
        starImage:"/public/images/Star 1.png",
      },
      {
        date: "DEC 03",
        title: "Global Engineering Education Expo 2023",
        type: "The St. Regis, Mumbai",
        time: "10 AM - 2 PM",
        code: "FREE .",
        interested: "48 interested",
        image: "/public/images/Image4.png",
        starImage:"/public/images/Star 1.png",
      },
      {
        date: "DEC 08",
        title: "Cricket Business Meetup",
        type: "Play The Turf, Malad, Mumbai",
        time: "6:30 PM - 9:30 PM",
        code: "INR 399.",
        image: "/public/images/Image5.png",
        starImage:"/public/images/Star 1.png",
      },
      {
        date: "FEB 14",
        title: "Valentine's Day Sail on a Yacht in Mumbai",
        type: "Mumbai",
        time: "7 aM - 8 PM",
        code: "",
        interested: "160 interested",
        image: "/public/images/Image6.png",
        starImage:"/public/images/Star 1.png",
      },
    ];
    
    export default items